---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
env:
  PYTHON_VERSION: "3.11"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Upgrade pip
        run: |
          python3 -m pip install --constraint=.github/workflows/constraints.txt pip
          python3 -m pip --version

      - name: Install test dependencies
        run: |
          python3 -m pip install -r .github/workflows/requirements.txt -c .github/workflows/constraints.txt

      - name: Run linter
        run: ansible-lint

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos7
          - centos8
          - debian8
          - debian9
          - debian10
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-docker yamllint ansible-lint docker netaddr dnspython

      - name: Run Molecule Primary/Secondary/Forwarder tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}

      - name: Run Molecule Shared Inventory tests
        run: molecule test --scenario-name shared_inventory
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
